# Generated by Django 2.2.2 on 2019-06-05 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='times',
            old_name='user_id',
            new_name='user',
        ),
    ]
